import { EngineConfigurationOption, NameText, UnitText } from 'sonolus-core'

export const optionsDefinition = {
    autoplay: {
        name: NameText.AutoPlay,
        scope: 'Taiko',
        standard: true,
        type: 'toggle',
        def: 0,
    },
    speed: {
        name: NameText.LevelSpeed,
        standard: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    hidden: {
        name: NameText.Hidden,
        standard: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    drumSize: {
        name: 'Drum Size',
        scope: 'Taiko',
        type: 'slider',
        def: 0.45,
        min: 0.05,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    slotPosition: {
        name: NameText.SlotPosition,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.05,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    noteSpeed: {
        name: NameText.NoteSpeed,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    sfxEnabled: {
        name: NameText.SFX,
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: NameText.AutoSFX,
        scope: 'Taiko',
        type: 'toggle',
        def: 0,
    },
    noteSize: {
        name: NameText.NoteSize,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    noteEffectEnabled: {
        name: NameText.NoteEffect,
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: NameText.NoteEffectSize,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    slotEffectEnabled: {
        name: NameText.SlotEffect,
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    slotEffectSize: {
        name: NameText.SlotEffectSize,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    stageCover: {
        name: NameText.HorizontalStageCover,
        scope: 'Taiko',
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
} satisfies Record<string, EngineConfigurationOption>
