import { EngineConfigurationOption, Text } from '@sonolus/core'

export const optionsDefinition = {
    speed: {
        name: Text.Speed,
        category: 'gameplay',
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        category: 'gameplay',
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    drumSize: {
        name: 'Drum Size',
        category: 'graphics',
        scope: 'Taiko',
        type: 'slider',
        def: 0.45,
        min: 0.05,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    slotPosition: {
        name: Text.SlotPosition,
        category: 'graphics',
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.05,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        category: 'gameplay',
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    sfxEnabled: {
        name: Text.Effect,
        category: 'audio',
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        category: 'audio',
        scope: 'Taiko',
        type: 'toggle',
        def: 0,
    },
    noteSize: {
        name: Text.NoteSize,
        category: 'graphics',
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        category: 'graphics',
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: Text.NoteEffectSize,
        category: 'graphics',
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    slotEffectEnabled: {
        name: Text.SlotEffect,
        category: 'graphics',
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    slotEffectSize: {
        name: Text.SlotEffectSize,
        category: 'graphics',
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    stageCover: {
        name: Text.StageCoverHorizontal,
        category: 'graphics',
        scope: 'Taiko',
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    stageDirection: {
        name: Text.StageDirection,
        category: 'graphics',
        scope: 'Taiko',
        type: 'select',
        def: 0,
        values: [Text.Left, Text.Up],
    },
    previewHorizontalScale: {
        name: Text.PreviewScaleHorizontal,
        category: 'miscellaneous',
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    previewMeasure: {
        name: Text.PreviewMeasure,
        category: 'miscellaneous',
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    previewBeat: {
        name: Text.PreviewBeat,
        category: 'miscellaneous',
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    previewTime: {
        name: Text.PreviewTime,
        category: 'miscellaneous',
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    previewBpm: {
        name: Text.PreviewBpm,
        category: 'miscellaneous',
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
} satisfies Record<string, EngineConfigurationOption>
