import { EngineConfigurationOption, Text } from '@sonolus/core'

export const optionsDefinition = {
    speed: {
        name: Text.Speed,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    drumSize: {
        name: 'Drum Size',
        scope: 'Taiko',
        type: 'slider',
        def: 0.45,
        min: 0.05,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    slotPosition: {
        name: Text.SlotPosition,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.05,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    sfxEnabled: {
        name: Text.Effect,
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        scope: 'Taiko',
        type: 'toggle',
        def: 0,
    },
    noteSize: {
        name: Text.NoteSize,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: Text.NoteEffectSize,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    slotEffectEnabled: {
        name: Text.SlotEffect,
        scope: 'Taiko',
        type: 'toggle',
        def: 1,
    },
    slotEffectSize: {
        name: Text.SlotEffectSize,
        scope: 'Taiko',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    stageCover: {
        name: Text.StageCoverHorizontal,
        scope: 'Taiko',
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
} satisfies Record<string, EngineConfigurationOption>
